packages:
  - packages/desktop
  - packages/core
  - packages/player
  - packages/web
  - packages/plugin-sdk
  - packages/desktop/plugins/*

onlyBuiltDependencies:
  - electron
  - esbuild
  - vue-demi
