packages:
  - packages/desktop
  - packages/core
  - packages/player
  - packages/web
  - packages/plugin-sdk
  - packages/plugin-template
  - packages/ringtone-factory
  - packages/rpc
  - packages/control-server
  - packages/control-protocol
  - packages/control-console
  - packages/desktop/plugins/*

onlyBuiltDependencies:
  - electron
  - esbuild
  - vue-demi
