/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue';

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TButton: typeof import('tdesign-vue-next')['Button']
    TInput: typeof import('tdesign-vue-next')['Input']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSlider: typeof import('tdesign-vue-next')['Slider']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TSwitch: typeof import('tdesign-vue-next')['Switch']
    TTag: typeof import('tdesign-vue-next')['Tag']
  }
}

// For TSX support
declare global {
  const RouterLink: (typeof import('vue-router'))['RouterLink'];
  const RouterView: (typeof import('vue-router'))['RouterView'];
  const TButton: (typeof import('tdesign-vue-next'))['Button'];
  const TInput: (typeof import('tdesign-vue-next'))['Input'];
  const TSelect: (typeof import('tdesign-vue-next'))['Select'];
  const TSlider: (typeof import('tdesign-vue-next'))['Slider'];
  const TSpace: (typeof import('tdesign-vue-next'))['Space'];
  const TSwitch: (typeof import('tdesign-vue-next'))['Switch'];
  const TTag: (typeof import('tdesign-vue-next'))['Tag'];
}
