/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue';

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TAlert: typeof import('tdesign-vue-next')['Alert']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TBreadcrumb: typeof import('tdesign-vue-next')['Breadcrumb']
    TBreadcrumbItem: typeof import('tdesign-vue-next')['BreadcrumbItem']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDescriptions: typeof import('tdesign-vue-next')['Descriptions']
    TDescriptionsItem: typeof import('tdesign-vue-next')['DescriptionsItem']
    TDropdown: typeof import('tdesign-vue-next')['Dropdown']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    THeader: typeof import('tdesign-vue-next')['Header']
    THeadMenu: typeof import('tdesign-vue-next')['HeadMenu']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TInput: typeof import('tdesign-vue-next')['Input']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TMenu: typeof import('tdesign-vue-next')['Menu']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TStepItem: typeof import('tdesign-vue-next')['StepItem']
    TSteps: typeof import('tdesign-vue-next')['Steps']
    TSubmenu: typeof import('tdesign-vue-next')['Submenu']
    TTag: typeof import('tdesign-vue-next')['Tag']
    TTooltip: typeof import('tdesign-vue-next')['Tooltip']
  }
}

// For TSX support
declare global {
  const RouterLink: (typeof import('vue-router'))['RouterLink'];
  const RouterView: (typeof import('vue-router'))['RouterView'];
  const TAlert: (typeof import('tdesign-vue-next'))['Alert'];
  const TAside: (typeof import('tdesign-vue-next'))['Aside'];
  const TBreadcrumb: (typeof import('tdesign-vue-next'))['Breadcrumb'];
  const TBreadcrumbItem: (typeof import('tdesign-vue-next'))['BreadcrumbItem'];
  const TButton: (typeof import('tdesign-vue-next'))['Button'];
  const TCard: (typeof import('tdesign-vue-next'))['Card'];
  const TContent: (typeof import('tdesign-vue-next'))['Content'];
  const TDescriptions: (typeof import('tdesign-vue-next'))['Descriptions'];
  const TDescriptionsItem: (typeof import('tdesign-vue-next'))['DescriptionsItem'];
  const TDropdown: (typeof import('tdesign-vue-next'))['Dropdown'];
  const TForm: (typeof import('tdesign-vue-next'))['Form'];
  const TFormItem: (typeof import('tdesign-vue-next'))['FormItem'];
  const THeader: (typeof import('tdesign-vue-next'))['Header'];
  const THeadMenu: (typeof import('tdesign-vue-next'))['HeadMenu'];
  const TIcon: (typeof import('tdesign-vue-next'))['Icon'];
  const TInput: (typeof import('tdesign-vue-next'))['Input'];
  const TLayout: (typeof import('tdesign-vue-next'))['Layout'];
  const TLoading: (typeof import('tdesign-vue-next'))['Loading'];
  const TMenu: (typeof import('tdesign-vue-next'))['Menu'];
  const TMenuItem: (typeof import('tdesign-vue-next'))['MenuItem'];
  const TStepItem: (typeof import('tdesign-vue-next'))['StepItem'];
  const TSteps: (typeof import('tdesign-vue-next'))['Steps'];
  const TSubmenu: (typeof import('tdesign-vue-next'))['Submenu'];
  const TTag: (typeof import('tdesign-vue-next'))['Tag'];
  const TTooltip: (typeof import('tdesign-vue-next'))['Tooltip'];
}
