/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue';

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DeviceOperationButtons: typeof import('./src/components/device-operation-buttons/index.vue')['default']
    DotField: typeof import('./src/components/dot-field/index.vue')['default']
    MetricTile: typeof import('./src/components/metric-tile/index.vue')['default']
    PageHeader: typeof import('./src/components/page-header/index.vue')['default']
    Result: typeof import('./src/components/result/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TAlert: typeof import('tdesign-vue-next')['Alert']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TAvatar: typeof import('tdesign-vue-next')['Avatar']
    TBadge: typeof import('tdesign-vue-next')['Badge']
    TBreadcrumb: typeof import('tdesign-vue-next')['Breadcrumb']
    TBreadcrumbItem: typeof import('tdesign-vue-next')['BreadcrumbItem']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TCascader: typeof import('tdesign-vue-next')['Cascader']
    TCheckbox: typeof import('tdesign-vue-next')['Checkbox']
    TCol: typeof import('tdesign-vue-next')['Col']
    TCollapse: typeof import('tdesign-vue-next')['Collapse']
    TCollapsePanel: typeof import('tdesign-vue-next')['CollapsePanel']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDatePicker: typeof import('tdesign-vue-next')['DatePicker']
    TDescriptions: typeof import('tdesign-vue-next')['Descriptions']
    TDescriptionsItem: typeof import('tdesign-vue-next')['DescriptionsItem']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TDivider: typeof import('tdesign-vue-next')['Divider']
    TDrawer: typeof import('tdesign-vue-next')['Drawer']
    TDropdown: typeof import('tdesign-vue-next')['Dropdown']
    TDropdownItem: typeof import('tdesign-vue-next')['DropdownItem']
    TDropdownMenu: typeof import('tdesign-vue-next')['DropdownMenu']
    TEmpty: typeof import('tdesign-vue-next')['Empty']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    THeader: typeof import('tdesign-vue-next')['Header']
    THeadMenu: typeof import('tdesign-vue-next')['HeadMenu']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TInput: typeof import('tdesign-vue-next')['Input']
    TInputNumber: typeof import('tdesign-vue-next')['InputNumber']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TLink: typeof import('tdesign-vue-next')['Link']
    TList: typeof import('tdesign-vue-next')['List']
    TListItem: typeof import('tdesign-vue-next')['ListItem']
    TListItemMeta: typeof import('tdesign-vue-next')['ListItemMeta']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TMenu: typeof import('tdesign-vue-next')['Menu']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TPagination: typeof import('tdesign-vue-next')['Pagination']
    TPopconfirm: typeof import('tdesign-vue-next')['Popconfirm']
    TPopup: typeof import('tdesign-vue-next')['Popup']
    TProgress: typeof import('tdesign-vue-next')['Progress']
    TRadio: typeof import('tdesign-vue-next')['Radio']
    TRadioButton: typeof import('tdesign-vue-next')['RadioButton']
    TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
    TRow: typeof import('tdesign-vue-next')['Row']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TStatistic: typeof import('tdesign-vue-next')['Statistic']
    TStepItem: typeof import('tdesign-vue-next')['StepItem']
    TSteps: typeof import('tdesign-vue-next')['Steps']
    TSubmenu: typeof import('tdesign-vue-next')['Submenu']
    TSwitch: typeof import('tdesign-vue-next')['Switch']
    TTable: typeof import('tdesign-vue-next')['Table']
    TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
    TTabs: typeof import('tdesign-vue-next')['Tabs']
    TTag: typeof import('tdesign-vue-next')['Tag']
    TTextarea: typeof import('tdesign-vue-next')['Textarea']
    TTooltip: typeof import('tdesign-vue-next')['Tooltip']
    TTree: typeof import('tdesign-vue-next')['Tree']
    TUpload: typeof import('tdesign-vue-next')['Upload']
  }
}

// For TSX support
declare global {
  const DeviceOperationButtons: (typeof import('./src/components/device-operation-buttons/index.vue'))['default'];
  const DotField: (typeof import('./src/components/dot-field/index.vue'))['default'];
  const MetricTile: (typeof import('./src/components/metric-tile/index.vue'))['default'];
  const PageHeader: (typeof import('./src/components/page-header/index.vue'))['default'];
  const Result: (typeof import('./src/components/result/index.vue'))['default'];
  const RouterLink: (typeof import('vue-router'))['RouterLink'];
  const RouterView: (typeof import('vue-router'))['RouterView'];
  const TAlert: (typeof import('tdesign-vue-next'))['Alert'];
  const TAside: (typeof import('tdesign-vue-next'))['Aside'];
  const TAvatar: (typeof import('tdesign-vue-next'))['Avatar'];
  const TBadge: (typeof import('tdesign-vue-next'))['Badge'];
  const TBreadcrumb: (typeof import('tdesign-vue-next'))['Breadcrumb'];
  const TBreadcrumbItem: (typeof import('tdesign-vue-next'))['BreadcrumbItem'];
  const TButton: (typeof import('tdesign-vue-next'))['Button'];
  const TCard: (typeof import('tdesign-vue-next'))['Card'];
  const TCascader: (typeof import('tdesign-vue-next'))['Cascader'];
  const TCheckbox: (typeof import('tdesign-vue-next'))['Checkbox'];
  const TCol: (typeof import('tdesign-vue-next'))['Col'];
  const TCollapse: (typeof import('tdesign-vue-next'))['Collapse'];
  const TCollapsePanel: (typeof import('tdesign-vue-next'))['CollapsePanel'];
  const TContent: (typeof import('tdesign-vue-next'))['Content'];
  const TDatePicker: (typeof import('tdesign-vue-next'))['DatePicker'];
  const TDescriptions: (typeof import('tdesign-vue-next'))['Descriptions'];
  const TDescriptionsItem: (typeof import('tdesign-vue-next'))['DescriptionsItem'];
  const TDialog: (typeof import('tdesign-vue-next'))['Dialog'];
  const TDivider: (typeof import('tdesign-vue-next'))['Divider'];
  const TDrawer: (typeof import('tdesign-vue-next'))['Drawer'];
  const TDropdown: (typeof import('tdesign-vue-next'))['Dropdown'];
  const TDropdownItem: (typeof import('tdesign-vue-next'))['DropdownItem'];
  const TDropdownMenu: (typeof import('tdesign-vue-next'))['DropdownMenu'];
  const TEmpty: (typeof import('tdesign-vue-next'))['Empty'];
  const TForm: (typeof import('tdesign-vue-next'))['Form'];
  const TFormItem: (typeof import('tdesign-vue-next'))['FormItem'];
  const THeader: (typeof import('tdesign-vue-next'))['Header'];
  const THeadMenu: (typeof import('tdesign-vue-next'))['HeadMenu'];
  const TIcon: (typeof import('tdesign-vue-next'))['Icon'];
  const TInput: (typeof import('tdesign-vue-next'))['Input'];
  const TInputNumber: (typeof import('tdesign-vue-next'))['InputNumber'];
  const TLayout: (typeof import('tdesign-vue-next'))['Layout'];
  const TLink: (typeof import('tdesign-vue-next'))['Link'];
  const TList: (typeof import('tdesign-vue-next'))['List'];
  const TListItem: (typeof import('tdesign-vue-next'))['ListItem'];
  const TListItemMeta: (typeof import('tdesign-vue-next'))['ListItemMeta'];
  const TLoading: (typeof import('tdesign-vue-next'))['Loading'];
  const TMenu: (typeof import('tdesign-vue-next'))['Menu'];
  const TMenuItem: (typeof import('tdesign-vue-next'))['MenuItem'];
  const TPagination: (typeof import('tdesign-vue-next'))['Pagination'];
  const TPopconfirm: (typeof import('tdesign-vue-next'))['Popconfirm'];
  const TPopup: (typeof import('tdesign-vue-next'))['Popup'];
  const TProgress: (typeof import('tdesign-vue-next'))['Progress'];
  const TRadio: (typeof import('tdesign-vue-next'))['Radio'];
  const TRadioButton: (typeof import('tdesign-vue-next'))['RadioButton'];
  const TRadioGroup: (typeof import('tdesign-vue-next'))['RadioGroup'];
  const TRow: (typeof import('tdesign-vue-next'))['Row'];
  const TSelect: (typeof import('tdesign-vue-next'))['Select'];
  const TSpace: (typeof import('tdesign-vue-next'))['Space'];
  const TStatistic: (typeof import('tdesign-vue-next'))['Statistic'];
  const TStepItem: (typeof import('tdesign-vue-next'))['StepItem'];
  const TSteps: (typeof import('tdesign-vue-next'))['Steps'];
  const TSubmenu: (typeof import('tdesign-vue-next'))['Submenu'];
  const TSwitch: (typeof import('tdesign-vue-next'))['Switch'];
  const TTable: (typeof import('tdesign-vue-next'))['Table'];
  const TTabPanel: (typeof import('tdesign-vue-next'))['TabPanel'];
  const TTabs: (typeof import('tdesign-vue-next'))['Tabs'];
  const TTag: (typeof import('tdesign-vue-next'))['Tag'];
  const TTextarea: (typeof import('tdesign-vue-next'))['Textarea'];
  const TTooltip: (typeof import('tdesign-vue-next'))['Tooltip'];
  const TTree: (typeof import('tdesign-vue-next'))['Tree'];
  const TUpload: (typeof import('tdesign-vue-next'))['Upload'];
}
